### ISSUE TITLE
Exeception in Dancer::Route line 190

### ISSUE THREAD

**Issue by jamesronan** [LoonyPandora/Dancer-Plugin-Passphrase#2]
As per issue #1, the docs weren't clear and as a result I stored  ->{hash} rather than the entire token.

If you do this, then pass it to ->matches() an exception is raised, which is not graceful at all.   The ->matches method should be capable of working out that it's been passed only the hash portion of the token and gracefully handle it (or potentially check all hashing mechs, after spitting out warnings that it's working, but slow because of the fact.

**Comment by LoonyPandora** [comment]
Had a look into this, it's not possible to match against just the output of `passphrase->hash`

Reason is, the output of `passphrase->hash` doesn't contain the salt used to generate that hash. So it's totally impossible to re-hash a plain text and test whether it matches.

Only option make it die in a more graceful manner, with a better error message.

The docs do mention you must pass a valid RFC2307, but I'll make that clearer - as per #1

**Comment by jamesronan** [comment]
Fair enough, a better error message - one that states that the passed hash doesn't look like an rfc2307 - would be fine.  

Also if you're improving the docs then that will do a long way to preventing this issue anyway :-)
