### ISSUE TITLE
Unicode error in test suite

### ISSUE THREAD

**Issue by davorg** [LoonyPandora/Dancer-Plugin-Passphrase#4]
```
$ prove -v -b t/007_unicode_matching.t 
t/007_unicode_matching.t .. 
1..4
Wide character in subroutine entry at /home/dave/rpm/BUILD/Dancer-Plugin-Passphrase-1.0.0/blib/lib/Dancer/Plugin/Passphrase.pm line 412.
# Looks like your test exited with 2 before it could output anything.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 4/4 subtests 

Test Summary Report
-------------------
t/007_unicode_matching.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 4 tests but ran 0.
Files=1, Tests=0,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.07 cusr  0.01 csys =  0.11 CPU)
Result: FAIL
```

This is Perl 5.16.2 on Fedora 18. But I see from cpantesters, that I'm not the only person with this issue.

http://www.cpantesters.org/cpan/report/4c58094a-4a2a-11e2-b452-f49d0790eac1
http://www.cpantesters.org/cpan/report/d1211046-4623-11e2-be4a-3ec746f78928

Haven't had time to investigate further. Might have a patch for you in the next few days.

Dave...

**Comment by LoonyPandora** [comment]
Installing 5.16.2 via perlbrew now to test this out.

**Comment by LoonyPandora** [comment]
Hmm, well I can't duplicate this on OS X 10.8 with perl 5.16.2 - this one might be tricky to resolve.

**Comment by LoonyPandora** [comment]
I have narrowed it down to a change in `Digest::SHA` v5.74, released at the end of November 2012. Earlier versions work fine, v5.74 or later fails.

In the changes for that version it mentions that this versions will `handle wide-string input by converting to bytes first` - which sounds related.

I'll continue to look into it to see whether it's something I can/should fix, or if it's an upstream issue.
