### ISSUE TITLE
user_roles does not accept realm and does not search

### ISSUE THREAD

**Issue by Casao** [LoonyPandora/Dancer-Plugin-Passphrase#9]
user_roles can be used to retrieve the roles of another user. 

However, it will not accept a realm to search, nor does it search amongst them all. It only works off of the realms of the current user.

**Comment by LoonyPandora** [comment]
This module doesn't have a `user_roles` method, and doesn't do anything with managing users and roles - it only does passwords.

Perhaps you are confusing it with [Dancer::Plugin::Auth::Extensible](https://metacpan.org/module/Dancer::Plugin::Auth::Extensible)?

**Comment by Casao** [comment]
Ah, sorry, clicked the link on the wrong tab.
